use_frameworks!

target 'MGFeedKit_Example' do
  pod 'MGFeedKit', :path => '../'
  pod 'GSImageViewerController'
  pod 'FeedKit', '~> 8.0'
  pod 'SwiftSoup'
  pod 'SDWebImage', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end
